name: CMake Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'centos:7'
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl -fsSLO --compressed https://cmake.org/files/v3.22/cmake-3.22.3-linux-x86_64.tar.gz
          tar -zxvf cmake-3.22.3-linux-x86_64.tar.gz -C /usr  --strip-components=1 --no-same-owner
          yum install -y which git wget rpm rpm-build cpio make glibc-devel glibc-headers libstdc++-static binutils openssl-devel libaio-devel
          rm -rf /usr/bin/cpp
      - name: Build with cmake
        run: mkdir buildenv && cd buildenv && ln -s `pwd`/deps/usr/local/oceanbase/devtools/bin/c++ /usr/bin/c++ && ln -s `pwd`/deps/usr/local/oceanbase/devtools/bin/cpp /usr/bin/cpp && ln -s `pwd`/deps/usr/local/oceanbase/devtools/bin/gcc /usr/bin/gcc && ln -s `pwd`/deps/usr/local/oceanbase/devtools/bin/g++ /usr/bin/g++ && ln -s `pwd`/deps/usr/local/oceanbase/devtools/bin/gcc-ar /usr/bin/gcc-ar && cmake .. && make -j 6
