name: CMake Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'centos:7'
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl -fsSLO --compressed https://cmake.org/files/v3.22/cmake-3.22.3-linux-x86_64.tar.gz
          tar -zxvf cmake-3.22.3-linux-x86_64.tar.gz -C /usr  --strip-components=1 --no-same-owner
          yum install -y which git wget rpm rpm-build cpio gcc gcc-c++ make glibc-devel glibc-headers libstdc++-static binutils openssl-devel libaio-devel
      - name: Build with cmake
        run: mkdir buildenv && cd buildenv && cmake .. && make -j 6
